name: Deploy to Lambda
on: [push]
jobs:
  deploy_source:
    name: Build and Deploy Lambda
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip output
        run: |
          cp -r package.json package-lock.json node_modules dist
          cd dist
          zip -qq -r ../bundle.zip *
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: tikTokPuppeteerFunction
          zip_file: bundle.zip
          runtime: nodejs18.x
